name: 'Set up CDK Environment'
description: 'Sets up Python, Node.js, CDK CLI, and AWS credentials'

inputs:
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true
    default: 'eu-central-1'
  python-version:
    description: 'Python version'
    required: false
    default: '3.11'
  node-version:
    description: 'Node.js version'
    required: false
    default: '20'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Restore cached dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          ~/.local/pip
          node_modules
        key: ${{ runner.os }}-deps-${{ hashFiles('**/requirements.txt', '**/package-lock.json') }}

    - name: Install dependencies
      shell: bash
      run: |
        npm install -g aws-cdk
        if [ ! -d "node_modules" ]; then
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        fi

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}