name: CDK Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Node.js (required for CDK CLI)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install -g aws-cdk
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1  # Change to your region

      - name: Bootstrap CDK
        id: bootstrap
        run: cdk bootstrap
        # The following line is optional but can be useful for debugging
        continue-on-error: false

      - name: CDK Diff (Preview changes)
        if: steps.bootstrap.outcome == 'success'
        run: cdk diff

      - name: Deploy with CDK
        if: steps.bootstrap.outcome == 'success'
        run: cdk deploy --all --require-approval never