name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'backend-api/**'
      - '.github/workflows/deploy-api.yml'
  workflow_dispatch:  # Allows manual triggering

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cdk_bootstrapped: ${{ steps.bootstrap.outputs.bootstrapped }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CDK environment
        uses: ./.github/actions/setup-cdk
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Bootstrap CDK
        id: bootstrap
        shell: bash
        run: |
          cdk bootstrap
          echo "bootstrapped=true" >> $GITHUB_OUTPUT
        continue-on-error: false

  deploy_networking:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CDK environment
        uses: ./.github/actions/setup-cdk
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy Networking Stack
        shell: bash
        run: cdk deploy FileProcessingNetwork --require-approval never

  deploy_storage:
    needs: deploy_networking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CDK environment
        uses: ./.github/actions/setup-cdk
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy Storage Stack
        shell: bash
        run: cdk deploy FileProcessingStorage --require-approval never

  deploy_database:
    needs: deploy_networking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CDK environment
        uses: ./.github/actions/setup-cdk
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy Database Stack
        shell: bash
        run: cdk deploy FileProcessingDatabase --require-approval never

  deploy_lambda:
    needs: [deploy_storage, deploy_database]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CDK environment
        uses: ./.github/actions/setup-cdk
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy Lambda Stack
        shell: bash
        run: cdk deploy FileProcessingCompute --require-approval never

  deploy_api:
    needs: [deploy_database, deploy_networking]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CDK environment
        uses: ./.github/actions/setup-cdk
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy API Stack
        shell: bash
        run: cdk deploy FileProcessingBackendApi --require-approval never