name: Deploy Backend API

on:
  push:
    branches: [main]
    paths:
      - 'backend-api/**'
      - '.github/workflows/deploy-api.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get ECR repository name
        id: repo-info
        run: |
          REPO_NAME=$(aws cloudformation list-exports --query "Exports[?Name=='ApiRepositoryName'].Value" --output text)
          # Set default if CloudFormation export not found
          if [ -z "$REPO_NAME" ]; then
            REPO_NAME="file-processing-api"
          fi
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_OUTPUT

      - name: Ensure ECR repository exists
        run: |
          REPO_NAME="${{ steps.repo-info.outputs.REPO_NAME }}"
          # Check if repository exists, create it if it doesn't
          aws ecr describe-repositories --repository-names $REPO_NAME 2>/dev/null || \
          aws ecr create-repository --repository-name $REPO_NAME

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ steps.repo-info.outputs.REPO_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd backend-api
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Get ECS service info
        id: ecs-info
        run: |
          CLUSTER_NAME=$(aws cloudformation list-exports --query "Exports[?Name=='ApiClusterName'].Value" --output text)
          SERVICE_NAME=$(aws cloudformation list-exports --query "Exports[?Name=='ApiServiceName'].Value" --output text)
          
          # Set default values if CloudFormation exports not found
          if [ -z "$CLUSTER_NAME" ]; then
            CLUSTER_NAME="your-default-cluster-name"  # Replace with your actual default
          fi
          
          if [ -z "$SERVICE_NAME" ]; then
            SERVICE_NAME="your-default-service-name"  # Replace with your actual default
          fi
          
          echo "CLUSTER_NAME=$CLUSTER_NAME" >> $GITHUB_OUTPUT
          echo "SERVICE_NAME=$SERVICE_NAME" >> $GITHUB_OUTPUT

      - name: Update ECS service
        run: |
          CLUSTER_NAME="${{ steps.ecs-info.outputs.CLUSTER_NAME }}"
          SERVICE_NAME="${{ steps.ecs-info.outputs.SERVICE_NAME }}"
          
          if [ -n "$CLUSTER_NAME" ] && [ -n "$SERVICE_NAME" ]; then
            # Check if service exists before updating
            aws ecs describe-services --cluster $CLUSTER_NAME --services $SERVICE_NAME --query "services[0].status" 2>/dev/null || \
            (echo "ECS service $SERVICE_NAME does not exist in cluster $CLUSTER_NAME. Please create it first." && exit 1)
            
            aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment
            echo "Successfully updated ECS service"
          else
            echo "Unable to find ECS cluster and service names. Make sure the stack is deployed first."
            exit 1
          fi